dataset:
  global_sampling_rate: null
  modality_config:
    screen:
      keep_nans : False
      sampling_rate: null
      offset: 0
      valid_condition:
        tier: "train"
      sample_stride: 4
      include_blanks: True
      interpolation:
        interpolation_mode: "nearest_neighbor"
    responses:
      keep_nans : False
      sampling_rate: null
      offset: 0.1 # in seconds
      interpolation:
        interpolation_mode: "nearest_neighbor"

dataloader:
  batch_size: 32
  shuffle: true
  num_workers: 1
  pin_memory: True
  drop_last: True
  prefetch_factor: 1
  shuffle_each_epoch: True



